*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*
Universidad de San Carlos de Guatemala
Faculta de Ingenieria
Arquitectura de Computadores y Ensambladores 1
Segundo Semestre 2016
Seccion A
*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*-*

Reporte Salida: 11:14 21/10/16
Lista Original: 2 78 15 3 88 14 7
Numeros Pares: 2 78 88 14 
Numeros Impares: 15 3 7
Numeros Primos: 2 3 7 
Numeros orden ascendente: 
Numeros orden descendente: 